from service.settings import ENV_APP

CONFIG = ENV_APP['AUTH']

# Настройки JWT

SECRET_KEY = str(CONFIG["SECRET_KEY"]).encode()
ALGORITHM = CONFIG["ALGORITHM_JWT"]
ACCESS_LIFETIME = int(CONFIG['ACCESS_LIFETIME'])
REFRESH_LIFETIME = int(CONFIG['REFRESH_LIFETIME'])
