# Generated by Django 5.2 on 2025-07-03 14:08

import money.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyaggregation',
            name='period',
        ),
        migrations.RemoveField(
            model_name='moneyaggregation',
            name='total_profit',
        ),
        migrations.RemoveField(
            model_name='moneyaggregation',
            name='total_transaction',
        ),
        migrations.AddField(
            model_name='moneyaggregation',
            name='payload',
            field=models.JSONField(default=dict, validators=[money.models.validate_payload]),
        ),
    ]
