# Generated by Django 5.2 on 2025-07-05 11:53

import django.db.models.deletion
import money.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_finaudit_delete_moneyaggregation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict, validators=[money.models.validate_payload])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audit',
                'db_table': 'content"."audit',
            },
        ),
        migrations.DeleteModel(
            name='FinAudit',
        ),
    ]
