# Generated by Django 5.2 on 2025-07-05 12:37

import django.db.models.deletion
import money.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_audit_delete_finaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=list, validators=[money.models.validate_payload])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AuditFin',
                'verbose_name_plural': 'AuditFin',
                'db_table': 'content"."auditfin',
            },
        ),
        migrations.DeleteModel(
            name='Audit',
        ),
    ]
