# Generated by Django 5.2 on 2025-07-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_auditfin_delete_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
