# Generated by Django 5.2 on 2025-11-09 15:52

import money.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0008_remove_cards_enable_cards_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditfin',
            name='payload',
            field=models.JSONField(default=list, null=True, validators=[money.models.validate_payload]),
        ),
    ]
